# Generated by Django 3.0.2 on 2020-01-10 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_auto_20200110_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=100)),
                ('prenom', models.CharField(db_column='Prenom', max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('etat', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Commande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='Libelle', max_length=200)),
                ('type', models.CharField(max_length=14)),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'Element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='Libelle', max_length=200)),
                ('prix_total', models.FloatField(blank=True, null=True)),
                ('titre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=100)),
                ('prenom', models.CharField(db_column='Prenom', max_length=100)),
                ('ville', models.CharField(db_column='ville', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100)),
                ('date_naissance', models.DateField(db_column='date_naissance')),
                ('login', models.CharField(db_column='login', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'Proprietaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('nb_personnes', models.IntegerField()),
                ('etat', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('numero_table', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationTables',
            fields=[
                ('reservation', models.OneToOneField(db_column='reservation', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.Reservation')),
            ],
            options={
                'db_table': 'Reservation_tables',
                'managed': False,
            },
        ),
    ]
